services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sellflow-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SellFlow@123456"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    container_name: sellflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  sqlserver_data:
  rabbitmq_data:
