"""cria tabela de produtos

Revision ID: 49794418a1d1
Revises: 37740bdad66a
Create Date: 2026-09-12 16:38:49.663695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49794418a1d1'
down_revision: Union[str, Sequence[str], None] = '37740bdad66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('principio_ativo', sa.String(length=200), nullable=True),
    sa.Column('concentracao', sa.String(length=100), nullable=True),
    sa.Column('forma_farmaceutica', sa.String(length=100), nullable=True),
    sa.Column('apresentacao', sa.String(length=200), nullable=True),
    sa.Column('fabricante', sa.String(length=200), nullable=True),
    sa.Column('registro_anvisa', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    # ### end Alembic commands ###
